// One-time generator: rewrites api/_schools.ts from (a) the existing curated
// metadata (name/district/address/city/zone_class) and (b) the finalized coords
// in scripts/curated-coords.json. Coordinates are copied verbatim from the JSON —
// never typed by hand — so provenance stays intact.
//
//   Run:  bun run scripts/gen-curated.ts   (after build-schools.ts)

import { SCHOOLS as OLD } from "../api/_schools";
import { readFileSync, writeFileSync } from "node:fs";

const coords = JSON.parse(readFileSync(new URL("./curated-coords.json", import.meta.url).pathname, "utf8"));
const byId = new Map(coords.map((c: any) => [c.id, c]));

const records = OLD.map((s) => {
  const c: any = byId.get(s.id);
  if (!c) throw new Error(`no finalized coord for curated school ${s.id}`);
  if (!["cde_provided", "geocoded_census", "geocoded_geoapify"].includes(c.coord_source))
    throw new Error(`invalid coord_source for ${s.id}: ${c.coord_source}`);
  const o: any = {
    id: s.id, name: s.name, district: s.district, address: s.address, city: s.city,
    lat: c.lat, lng: c.lng, zone_class: s.zone_class,
  };
  if (c.cds) o.cds = c.cds;
  o.source = "curated";
  o.coord_source = c.coord_source;
  return o;
});

const body = records
  .map((r) => {
    const lines = Object.entries(r).map(([k, v]) => `    ${k}: ${JSON.stringify(v)},`).join("\n");
    return `  {\n${lines}\n  },`;
  })
  .join("\n");

const file = `// Schools directory for the "schools near you" radius lookup and name search.
//
// Two provenance tiers, deliberately kept distinct (see the \`source\` field):
//   - "curated": ${records.length} East Bay schools individually verified by a human. Their
//     coordinates were re-confirmed for this build against the CDE directory and,
//     where CDE differed, an independent geocode — see \`coord_source\`.
//   - "cde": the bulk California public-school set imported from the California
//     Department of Education directory (api/_schools_cde.json). Built offline by
//     scripts/build-schools.ts; see scripts/schools-manifest.json for provenance.
//
// COORDINATE INTEGRITY: every lat/lng below traces to either a CDE-published
// coordinate or a real geocode call (never hand-typed). This file is generated by
// scripts/gen-curated.ts — edit metadata there or in the build script, not by hand.

import cdeRaw from "./_schools_cde.json";

export interface School {
  id: string;
  name: string;
  district: string;
  address: string;
  city: string;
  lat: number;
  lng: number;
  // Where this record came from: a human-verified pick vs. the bulk CDE import.
  source: "curated" | "cde";
  // How the coordinate was obtained (auditable provenance).
  coord_source: "cde_provided" | "geocoded_census" | "geocoded_geoapify";
  // Curated-only: hand-classified fire context. CDE bulk records are not
  // hand-classified, so this is absent for them (treated as non-hills-adjacent).
  //   "hills" = in/adjacent to WUI, "ridge" = ridge-adjacent, "flats" = valley floor
  zone_class?: "hills" | "ridge" | "flats";
  // Curated-only: the matched CDE CDSCode, linking the verified pick to its
  // authoritative record (and used to dedup it out of the bulk set at build time).
  cds?: string;
  // CDE-only extras, useful for name search.
  zip?: string;
  county?: string;
}

// Individually human-verified East Bay schools. Kept distinct from the bulk CDE
// set because the project's trust model rests on being precise about what is
// verified vs. sourced in bulk.
export const SCHOOLS: School[] = [
${body}
];

// Bulk California public schools from the CDE directory (source: "cde").
export const CDE_SCHOOLS: School[] = cdeRaw as School[];

// Everything the radius/search endpoint queries. Curated first so a curated pick
// wins id ties (the matching CDE row is deduped out at build time, so there are
// none in practice).
export const ALL_SCHOOLS: School[] = [...SCHOOLS, ...CDE_SCHOOLS];

const _byId: Map<string, School> = new Map(ALL_SCHOOLS.map((s) => [s.id, s]));

export function findSchool(id: string): School | undefined {
  return _byId.get(id);
}
`;

writeFileSync(new URL("../api/_schools.ts", import.meta.url).pathname, file);
console.log(`Wrote api/_schools.ts — ${records.length} curated records`);
console.log("coord_source:", records.reduce((a: any, r: any) => ((a[r.coord_source] = (a[r.coord_source] || 0) + 1), a), {}));
