// Schools directory for the "schools near you" radius lookup and name search.
//
// Two provenance tiers, deliberately kept distinct (see the `source` field):
//   - "curated": 27 East Bay schools individually verified by a human. Their
//     coordinates were re-confirmed for this build against the CDE directory and,
//     where CDE differed, an independent geocode — see `coord_source`.
//   - "cde": the bulk California public-school set imported from the California
//     Department of Education directory (api/_schools_cde.json). Built offline by
//     scripts/build-schools.ts; see scripts/schools-manifest.json for provenance.
//
// COORDINATE INTEGRITY: every lat/lng below traces to either a CDE-published
// coordinate or a real geocode call (never hand-typed). This file is generated by
// scripts/gen-curated.ts — edit metadata there or in the build script, not by hand.

import cdeRaw from "./_schools_cde.json";

export interface School {
  id: string;
  name: string;
  district: string;
  address: string;
  city: string;
  lat: number;
  lng: number;
  // Where this record came from: a human-verified pick vs. the bulk CDE import.
  source: "curated" | "cde";
  // How the coordinate was obtained (auditable provenance).
  coord_source: "cde_provided" | "geocoded_census" | "geocoded_geoapify";
  // Curated-only: hand-classified fire context. CDE bulk records are not
  // hand-classified, so this is absent for them (treated as non-hills-adjacent).
  //   "hills" = in/adjacent to WUI, "ridge" = ridge-adjacent, "flats" = valley floor
  zone_class?: "hills" | "ridge" | "flats";
  // Curated-only: the matched CDE CDSCode, linking the verified pick to its
  // authoritative record (and used to dedup it out of the bulk set at build time).
  cds?: string;
  // CDE-only extras, useful for name search.
  zip?: string;
  county?: string;
}

// Individually human-verified East Bay schools. Kept distinct from the bulk CDE
// set because the project's trust model rests on being precise about what is
// verified vs. sourced in bulk.
export const SCHOOLS: School[] = [
  {
    id: "skyline-oakland",
    name: "Skyline High School",
    district: "Oakland Unified",
    address: "12250 Skyline Blvd",
    city: "Oakland",
    lat: 37.79749,
    lng: -122.1636,
    zone_class: "hills",
    cds: "01612590137943",
    source: "curated",
    coord_source: "cde_provided",
  },
  {
    id: "oakland-tech",
    name: "Oakland Technical High School",
    district: "Oakland Unified",
    address: "4351 Broadway",
    city: "Oakland",
    lat: 37.83172,
    lng: -122.25413,
    zone_class: "flats",
    cds: "01612590136051",
    source: "curated",
    coord_source: "cde_provided",
  },
  {
    id: "berkeley-high",
    name: "Berkeley High School",
    district: "Berkeley Unified",
    address: "1980 Allston Way",
    city: "Berkeley",
    lat: 37.86891,
    lng: -122.2712,
    zone_class: "flats",
    cds: "01611430131177",
    source: "curated",
    coord_source: "cde_provided",
  },
  {
    id: "castro-valley-high",
    name: "Castro Valley High School",
    district: "Castro Valley Unified",
    address: "19400 Santa Maria Ave",
    city: "Castro Valley",
    lat: 37.70518,
    lng: -122.07847,
    zone_class: "hills",
    cds: "01611500132225",
    source: "curated",
    coord_source: "cde_provided",
  },
  {
    id: "hayward-high",
    name: "Hayward High School",
    district: "Hayward Unified",
    address: "1633 East Ave",
    city: "Hayward",
    lat: 37.6744,
    lng: -122.06839,
    zone_class: "ridge",
    cds: "01611920133629",
    source: "curated",
    coord_source: "geocoded_census",
  },
  {
    id: "mount-eden-high",
    name: "Mt. Eden High School",
    district: "Hayward Unified",
    address: "2300 Panama St",
    city: "Hayward",
    lat: 37.62531,
    lng: -122.09056,
    zone_class: "flats",
    cds: "01611920135319",
    source: "curated",
    coord_source: "cde_provided",
  },
  {
    id: "mission-san-jose-high",
    name: "Mission San Jose High School",
    district: "Fremont Unified",
    address: "41717 Palm Ave",
    city: "Fremont",
    lat: 37.54504,
    lng: -121.93193,
    zone_class: "ridge",
    cds: "01611760135244",
    source: "curated",
    coord_source: "cde_provided",
  },
  {
    id: "irvington-high",
    name: "Irvington High School",
    district: "Fremont Unified",
    address: "41800 Blacow Rd",
    city: "Fremont",
    lat: 37.52305,
    lng: -121.96518,
    zone_class: "flats",
    cds: "01611760134270",
    source: "curated",
    coord_source: "geocoded_geoapify",
  },
  {
    id: "american-high",
    name: "American High School",
    district: "Fremont Unified",
    address: "36300 Fremont Blvd",
    city: "Fremont",
    lat: 37.56365,
    lng: -122.01747,
    zone_class: "flats",
    cds: "01611760130062",
    source: "curated",
    coord_source: "cde_provided",
  },
  {
    id: "washington-high",
    name: "Washington High School",
    district: "Fremont Unified",
    address: "38442 Fremont Blvd",
    city: "Fremont",
    lat: 37.55208,
    lng: -121.99484,
    zone_class: "flats",
    cds: "01611760138693",
    source: "curated",
    coord_source: "cde_provided",
  },
  {
    id: "kennedy-high",
    name: "John F. Kennedy High School",
    district: "Fremont Unified",
    address: "39999 Blacow Rd",
    city: "Fremont",
    lat: 37.52858,
    lng: -121.98743,
    zone_class: "flats",
    cds: "01611760134452",
    source: "curated",
    coord_source: "geocoded_geoapify",
  },
  {
    id: "amador-valley-high",
    name: "Amador Valley High School",
    district: "Pleasanton Unified",
    address: "1155 Santa Rita Rd",
    city: "Pleasanton",
    lat: 37.66783,
    lng: -121.87345,
    zone_class: "ridge",
    cds: "01751010130583",
    source: "curated",
    coord_source: "geocoded_census",
  },
  {
    id: "foothill-high",
    name: "Foothill High School",
    district: "Pleasanton Unified",
    address: "4375 Foothill Rd",
    city: "Pleasanton",
    lat: 37.67671,
    lng: -121.92161,
    zone_class: "ridge",
    cds: "01751010130096",
    source: "curated",
    coord_source: "geocoded_census",
  },
  {
    id: "campolindo-high",
    name: "Campolindo High School",
    district: "Acalanes Union High",
    address: "300 Moraga Rd",
    city: "Moraga",
    lat: 37.86447,
    lng: -122.1242,
    zone_class: "hills",
    cds: "07616300731125",
    source: "curated",
    coord_source: "geocoded_geoapify",
  },
  {
    id: "miramonte-high",
    name: "Miramonte High School",
    district: "Acalanes Union High",
    address: "750 Moraga Way",
    city: "Orinda",
    lat: 37.84233,
    lng: -122.14438,
    zone_class: "hills",
    cds: "07616300734244",
    source: "curated",
    coord_source: "cde_provided",
  },
  {
    id: "acalanes-high",
    name: "Acalanes High School",
    district: "Acalanes Union High",
    address: "1200 Pleasant Hill Rd",
    city: "Lafayette",
    lat: 37.90431,
    lng: -122.09906,
    zone_class: "hills",
    cds: "07616300730283",
    source: "curated",
    coord_source: "cde_provided",
  },
  {
    id: "camino-pablo-elem",
    name: "Camino Pablo Elementary School",
    district: "Moraga School District",
    address: "1111 Camino Pablo",
    city: "Moraga",
    lat: 37.82295,
    lng: -122.12456,
    zone_class: "hills",
    cds: "07617476003909",
    source: "curated",
    coord_source: "cde_provided",
  },
  {
    id: "los-perales-elem",
    name: "Los Perales Elementary School",
    district: "Moraga School District",
    address: "22 Wakefield Dr",
    city: "Moraga",
    lat: 37.84762,
    lng: -122.13826,
    zone_class: "hills",
    cds: "07617476003933",
    source: "curated",
    coord_source: "cde_provided",
  },
  {
    id: "rheem-elem",
    name: "Donald L. Rheem Elementary School",
    district: "Moraga School District",
    address: "90 Laird Dr",
    city: "Moraga",
    lat: 37.85761,
    lng: -122.13303,
    zone_class: "hills",
    cds: "07617476003917",
    source: "curated",
    coord_source: "cde_provided",
  },
  {
    id: "joaquin-moraga-intermediate",
    name: "Joaquin Moraga Intermediate School",
    district: "Moraga School District",
    address: "1010 Camino Pablo",
    city: "Moraga",
    lat: 37.82692,
    lng: -122.13063,
    zone_class: "hills",
    cds: "07617476003925",
    source: "curated",
    coord_source: "cde_provided",
  },
  {
    id: "del-rey-elem",
    name: "Del Rey Elementary School",
    district: "Orinda Union School District",
    address: "25 El Camino Moraga",
    city: "Orinda",
    lat: 37.8466,
    lng: -122.15395,
    zone_class: "hills",
    cds: "07617706004444",
    source: "curated",
    coord_source: "cde_provided",
  },
  {
    id: "glorietta-elem",
    name: "Glorietta Elementary School",
    district: "Orinda Union School District",
    address: "15 Martha Rd",
    city: "Orinda",
    lat: 37.87237,
    lng: -122.1624,
    zone_class: "hills",
    cds: "07617706004451",
    source: "curated",
    coord_source: "cde_provided",
  },
  {
    id: "sleepy-hollow-elem",
    name: "Sleepy Hollow Elementary School",
    district: "Orinda Union School District",
    address: "20 Washington Ln",
    city: "Orinda",
    lat: 37.90807,
    lng: -122.19876,
    zone_class: "hills",
    cds: "07617706004501",
    source: "curated",
    coord_source: "cde_provided",
  },
  {
    id: "wagner-ranch-elem",
    name: "Wagner Ranch Elementary School",
    district: "Orinda Union School District",
    address: "350 Camino Pablo",
    city: "Orinda",
    lat: 37.89793,
    lng: -122.20855,
    zone_class: "hills",
    cds: "07617706066583",
    source: "curated",
    coord_source: "cde_provided",
  },
  {
    id: "orinda-intermediate",
    name: "Orinda Intermediate School",
    district: "Orinda Union School District",
    address: "80 Ivy Dr",
    city: "Orinda",
    lat: 37.85121,
    lng: -122.14544,
    zone_class: "hills",
    cds: "07617706004477",
    source: "curated",
    coord_source: "cde_provided",
  },
  {
    id: "saklan-school",
    name: "The Saklan School",
    district: "Independent (PK-8)",
    address: "1678 School St",
    city: "Moraga",
    lat: 37.83316,
    lng: -122.13258,
    zone_class: "hills",
    source: "curated",
    coord_source: "geocoded_census",
  },
  {
    id: "st-perpetua-school",
    name: "St. Perpetua School",
    district: "Catholic (K-8)",
    address: "3454 Hamlin Rd",
    city: "Lafayette",
    lat: 37.88179,
    lng: -122.11336,
    zone_class: "hills",
    source: "curated",
    coord_source: "geocoded_census",
  },
];

// Bulk California public schools from the CDE directory (source: "cde").
export const CDE_SCHOOLS: School[] = cdeRaw as School[];

// Everything the radius/search endpoint queries. Curated first so a curated pick
// wins id ties (the matching CDE row is deduped out at build time, so there are
// none in practice).
export const ALL_SCHOOLS: School[] = [...SCHOOLS, ...CDE_SCHOOLS];

const _byId: Map<string, School> = new Map(ALL_SCHOOLS.map((s) => [s.id, s]));

export function findSchool(id: string): School | undefined {
  return _byId.get(id);
}
